# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_one <- function(x) {
    .Call(`_StrassenR_add_one`, x)
}

strassen_rcpp <- function(A, B) {
    .Call(`_StrassenR_strassen_rcpp`, A, B)
}

