# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Parallel Strassen's Matrix Multiplication
#'
#' Computes the matrix product of two matrices using a parallelized, hybrid
#' version of Strassen's algorithm. This is the fastest implementation in the
#' package for large matrices. It uses a threshold to switch to a naive
#' algorithm for smaller sub-problems and OpenMP to parallelize the recursive calls.
#'
#' @param A A numeric matrix.
#' @param B A numeric matrix.
#' @param threshold The matrix size at which the algorithm switches from Strassen's
#'   recursion to a naive multiplication. Defaults to 64.
#' @return The matrix product of A and B.
#' @export
strassen_parallel <- function(A, B, threshold = 64L) {
    .Call(`_StrassenR_strassen_parallel`, A, B, threshold)
}

#' Hybrid Strassen's Matrix Multiplication (Sequential)
#'
#' Computes the matrix product of two matrices using a sequential, hybrid
#' version of Strassen's algorithm. It uses a threshold to switch to a naive
#' algorithm for smaller sub-problems but does not use parallel processing.
#'
#' @param A A numeric matrix.
#' @param B A numeric matrix.
#' @param threshold The matrix size at which the algorithm switches from Strassen's
#'   recursion to a naive multiplication. Defaults to 64.
#' @return The matrix product of A and B.
#' @export
strassen_hybrid <- function(A, B, threshold = 64L) {
    .Call(`_StrassenR_strassen_hybrid`, A, B, threshold)
}

#' Pure Strassen's Matrix Multiplication (Recursive)
#'
#' Computes the matrix product of two matrices using the classic, pure
#' recursive Strassen's algorithm. This function is provided for educational
#' and benchmarking purposes to demonstrate the high overhead of recursion
#' without a hybrid strategy. It recurses down to a 1x1 matrix.
#'
#' @param A A numeric matrix.
#' @param B A numeric matrix.
#' @return The matrix product of A and B.
#' @export
strassen_pure_recursive <- function(A, B) {
    .Call(`_StrassenR_strassen_pure_recursive`, A, B)
}

#' Naive Matrix Multiplication (C++)
#'
#' Computes the matrix product of two matrices using a simple, three-loop
#' naive algorithm in C++. This function is provided for educational and
#' benchmarking purposes.
#'
#' @param A A numeric matrix.
#' @param B A numeric matrix.
#' @return The matrix product of A and B.
#' @export
naive_rcpp_multiply <- function(A, B) {
    .Call(`_StrassenR_naive_rcpp_multiply`, A, B)
}

